### ISSUE TITLE
generate empty files for loader on start

### ISSUE THREAD

**Issue by nik-kor** [alfa-bank-dev/bem-loader#3]
It's stupid to create empty files just for loader but it's necessary. So the better solution is to generate this temporary files

**Comment by nik-kor** [comment]
https://github.com/alfa-bank-dev/bem-css-loader/pull/8

**Comment by nik-kor** [comment]
@voischev @awinogradov @ziimir

**Comment by awinogradov** [comment]
:+1: can we drop `bem-css-loader/component.css` in the future?

**Comment by nik-kor** [comment]
@awinogradov do you mean not to write empty files just to use loader?

**Comment by awinogradov** [comment]
@nik-kor yes! Maybe we can add them automatically? Because they are need for our tools not for users.

**Comment by nik-kor** [comment]
@awinogradov yeah, u r right. Great idea!

**Comment by nik-kor** [comment]
@awinogradov done https://github.com/alfa-bank-dev/bem-css-loader/commit/5442030864d1b9a316b1b3a2cf362240652df29e

So the only thing you need to do is to require single stubs file

**Comment by awinogradov** [comment]
@nik-kor you are awesome! Can add it to example?:)

**Comment by nik-kor** [comment]
examples added to readme. We are going to test it with our library.
