### ISSUE TITLE
Publicate npm module and add versions

### ISSUE THREAD

**Issue by nik-kor** [alfa-bank-dev/bem-loader#4]

**Comment by nik-kor** [comment]
done https://www.npmjs.com/package/bem-css-loader

**Comment by voischev** [comment]
чего название не поменяли?) оно же не только css умеет

**Comment by nik-kor** [comment]
Bem-assets-loader?

ср, 17 Фев 2016, 0:25, Ivan Voischev <notifications@github.com>:

**Comment by awinogradov** [comment]
why not ;)

**Comment by voischev** [comment]
чем плох просто bem-loader? https://www.npmjs.com/search?q=bem-loader

**Comment by nik-kor** [comment]
да вообщем, тоже ок.)

**Comment by nik-kor** [comment]
@awinogradov Нам нужна организация в npm. Создашь?

**Comment by awinogradov** [comment]
хз, нужна ли) можно подумать)

**Comment by nik-kor** [comment]
это может быть полезно для публикации банковских модулей. Но оно платное -
поэтому, да можно подумать)


На самом деле, можно вообще не публиковать этот модуль, а тянуть напрямую
из гитхаба.

**Comment by awinogradov** [comment]
ну оно криво бесплатное)

**Comment by nik-kor** [comment]
@voischev переименовал

**Comment by voischev** [comment]
:+1:
